import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {spawnSync} from 'node:child_process';

const source=path.resolve('scripts/ao/orchestrator.mjs');
const temp=fs.mkdtempSync(path.join(os.tmpdir(),'ao-registry-test-'));
fs.mkdirSync(path.join(temp,'docs','ai'),{recursive:true});
fs.mkdirSync(path.join(temp,'.agents','skills','test-skill'),{recursive:true});
fs.writeFileSync(path.join(temp,'.agents','skills','test-skill','SKILL.md'),'---\nname: test-skill\ndescription: Used only by registry tests.\n---\n');
const leaf={mode:'subagent',permissions:[{action:'subagent',resource:'*',effect:'deny'},{action:'edit',resource:'*',effect:'allow'}]};
const reviewer={mode:'subagent',permissions:[{action:'subagent',resource:'*',effect:'deny'},{action:'edit',resource:'*',effect:'deny'}]};
fs.writeFileSync(path.join(temp,'opencode.json'),JSON.stringify({agents:{'ao-lead':{},'ao-recovery-orchestrator':{},'ao-implementation-orchestrator':{},'ao-verification-orchestrator':{},'ao-recovery-worker':leaf,'ao-frontend-worker':leaf,'ao-backend-worker':leaf,'ao-qa-reviewer':reviewer,'ao-security-reviewer':reviewer}}));
const baseTask=(id,scope)=>({task_id:id,title:id,goal:id,task_type:'test',domain:['test'],status:'READY',priority:'medium',owner_orchestrator:'ao-implementation-orchestrator',worker_session:null,required_skills:['test-skill'],recommended_skills:[],forbidden_skills:[],branch:`ao/${id.toLowerCase()}`,worktree:null,owned_files:[],owned_directories:[scope],readonly_scope:[],dependencies:[],acceptance_criteria:['pass'],required_tests:['test'],completion_predicates:['tests'],lease:null,latest_commit:null,pr:null,blocker:null,evidence:[],supersedes:[],duplicate_of:null,last_runtime_heartbeat:null,last_meaningful_progress:null});
const registry={schema_version:1,policy:{max_leaf_workers:6},tasks:[baseTask('AO-901','src/a'),baseTask('AO-902','src/a/nested'),baseTask('AO-903','src/b')]};
const registryPath=path.join(temp,'docs','ai','AO-TASK-REGISTRY.json');fs.writeFileSync(registryPath,JSON.stringify(registry,null,2));
const run=(...args)=>spawnSync(process.execPath,[source,...args],{cwd:temp,env:{...process.env,AO_REPO:temp,AO_REGISTRY:registryPath},encoding:'utf8'});
assert.equal(run('validate').status,0,'baseline validates');
assert.equal(run('acquire','AO-901','worker-a','30').status,0,'first lease acquired');
assert.notEqual(run('acquire','AO-902','worker-b','30').status,0,'overlapping write scope rejected');
assert.equal(run('acquire','AO-903','worker-c','30').status,0,'independent scope admitted');
assert.notEqual(run('transition','AO-901','LOCAL_VERIFIED').status,0,'verification without evidence rejected');
assert.equal(run('progress','AO-901','worker-a','diff produced').status,0,'meaningful progress recorded separately');
assert.equal(run('release','AO-901','worker-a','model fallback').status,0,'lease transfer releases same task');
assert.equal(run('acquire','AO-901','worker-d','30').status,0,'replacement gets same task');
const updated=JSON.parse(fs.readFileSync(registryPath,'utf8'));
assert.equal(updated.tasks[0].lease.generation,2,'lease generation increments');
assert.equal(updated.tasks.length,3,'fallback creates no new task');
console.log('AO scheduler failure-mode tests passed.');
